### PR TITLE
8.1 healthd

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
what about this ?

**Comment by jerpelea** [comment]
why are you closing this PR?

**Comment by alviteri** [comment]
How much time is needed to test this ?

**Comment by alviteri** [comment]
Which device is that ?

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/3f58d2eeaa14a949640a192a0f59a540d70c651d

**Comment by jerpelea** [comment]
loire and yoshino deivces

**Comment by alviteri** [comment]
I can't charge Nile or yoshino devices via USB/pc without this .... I will add this on sonyaosp

**Comment by jerpelea** [comment]
with the latest patches already merged yoshino is confirmed to charge properly over pc

**Comment by jerpelea** [comment]
please cleanup the 1c93ff8

**Comment by alviteri** [comment]
this happens because you don't have the new healthd
pioneer:/ # ls /persist/bms/batt_info.txt
ls: /persist/bms/batt_info.txt: No such file or directory

maple:/ # cd persist
maple:/persist # ls
alarm bluetooth bms data display drm hlos_rfs lost+found misc pc rfs secnvm sensors time vpp 
maple:/persist # cd bms
maple:/persist/bms # ls
batt_info.txt

**Comment by alviteri** [comment]
don't reopen ... this is needed for me only and i will add this on personal sources

**Comment by jerpelea** [comment]
looks better

**Comment by kholk** [comment]
Thanks for the update

**Comment by oshmoun** [comment]
tested offline charging on kugo, and it looks ok. Charger mode starts fine whether device is connected to pc or charging from wall

**Pull request merged**
