### PR TITLE
Reorder manifest.xml

### PR DESCRIPTION
**Pull request by luk1337**
* Now it matches lshal order.

### CODE REVIEW

**Comment by alviteri** [comment]
Sensors was removed due to broken sensor.qcom for Loire ping @oshmoun

**Comment by luk1337** [comment]
Uh, this defines it as passthrough so no need to ping him.

**Comment by alviteri** [comment]
Shouldn't be better use hwbinder ?

**Comment by luk1337** [comment]
Maybe I should have called it 'Regenerate manifest.xml' instead?

**Comment by alviteri** [comment]
Is ok as is called ...

**Comment by oshmoun** [comment]
The sensors service can probably be added back without issues, as the repeated restarting is now fixed with https://github.com/sonyxperiadev/device-sony-common/commit/7e242d54284ea84b3cc3083e3ce9d39c5abb22fd#diff-7757ae3d5fee7079ec3e1c9d061f4d29

**Comment by luk1337** [comment]
Then if you want to set it to hwbinder, do it in separate change please.

**Comment by luk1337** [comment]
^^ Ideally after this change gets merged.

**Pull request merged**
