### PR TITLE
manifest: add gnss service

### PR DESCRIPTION
**Pull request by oshmoun**
gnss service is built already, so add it in manifest to explicitly declare usage.

Change-Id: Ic39cf0f6edd636c6c30c1e4e9b1b571ea705ffc7

### CODE REVIEW

**Comment by oshmoun** [comment]
This requires https://github.com/sonyxperiadev/device-sony-sepolicy/pull/327

**Comment by humberos** [comment]
seems this patch breaks systemui on kagura.
yes, I've added sepolicy patch.

**Comment by humberos** [comment]
W zygote64: Waited one second for android.hardware.gnss@1.0::IGnss/default. Waiting another...

**Comment by oshmoun** [comment]
Weird
It's running fine here on both kugo and kagura
Can you confirm that the service has the correct context?

**Comment by humberos** [comment]
Hmmmm
Aosp or omni?

**Comment by oshmoun** [comment]
Tested on omni so far

**Comment by oshmoun** [comment]
Could you please check dmesg, to see if the service is not starting due to missing an selinux domain?

**Comment by humberos** [comment]
[    3.941270] init: service gnss_service does not have a SELinux domain defined

**Comment by oshmoun** [comment]
did you just build bootimage? That would explain this. Could you run restorecon and see if the domain of the service changes?

**Comment by humberos** [comment]
Sorry @oshmoun 
The problem is on my side due to dirty builds.

**Comment by oshmoun** [comment]
No problem :) 
good to know it works!

**Pull request merged**
