### PR TITLE
[DO NOT MERGE]sony-common: add Vendor Interface Object

### PR DESCRIPTION
**Pull request by alviteri**
kanged from marlin
https://android.googlesource.com/device/google/marlin/+/android-8.0.0_r3/compatibility_matrix.xml
https://android.googlesource.com/device/google/marlin/+/android-8.0.0_r3/manifest.xml

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by Bitti09** [comment]
07-24 20:14:52.892  1021  1021 W system_server: Waited one second for android.hardware.vibrator@1.0::IVibrator/default. Waiting another...

can't boot on  xz with this PR @alviteri

**Comment by alviteri** [comment]
let me finish service per service then we can merge this

**Comment by alviteri** [comment]
ok @Bitti09 to test this make sure you have merged the following PR

https://github.com/sonyxperiadev/device-sony-common/pull/311
https://github.com/sonyxperiadev/device-sony-sepolicy/pull/250
https://github.com/sonyxperiadev/device-sony-sepolicy/pull/251

**Comment by Bitti09** [comment]
ok @alviteri  will sync & build now

**Pull request merged**
