### PR TITLE
[master] Revert "init: speedup the boot process"

### PR DESCRIPTION
**Pull request by humberos**
This reverts commit 1c9a06052c858f31ad4653113ff0bfea685d299a.

Fix boot process for tone platform.

Change-Id: Ia9d75f969cdc33b182449fe12ff2a6490c672c7d

### CODE REVIEW

**Comment by humberos** [comment]
Please hold on, I will split this patch locally and try to figure out what service is breaking tone boot process

**Comment by jerpelea** [comment]
please update your device to the latest sw with Emma and use latest vendor
I tried to replicate the bug and devices boot normal

**Comment by humberos** [comment]
Device: Kagura
SW: 41.3.A.0.401
ODM: V6

@oshmoun also have the same issue on keyaki.

**Comment by oshmoun** [comment]
Yes can confirm,and I also on the latest fw (because i can flash odm through fastboot). Somehow tone doesn't like it when display services are started too early.

**Comment by humberos** [comment]
Thanks @oshmoun 
I will close this PR soon since it is only a reference to fix tone boot process.
I will test one by one of display services and see if there is a property that should be tested before the call statement.

**Comment by bartcubbins** [comment]
it's ok on suzu (k4.4) and tulip(k3.10) on 8.1.0_r1 with hwc2.0

**Comment by humberos** [comment]
Yeah, suzu and yoshino are ok!
Problem is on tone family.
Thanks for the confirmation @bartcubbins

**Comment by bartcubbins** [comment]
very strange

**Comment by humberos** [comment]
Ok!
I've found the issue.
It is custom bootanimation...

@jerpelea 
I am sorry. You're right.
There is no boot problem when I use default android bootanimation.

**Comment by oshmoun** [comment]
but a custom bootanim doesn't cause the same issue on loire (omni as an example)

**Comment by humberos** [comment]
yeah! too fast
I've got the bootloop again even by removing custom bootanimation

**Comment by humberos** [comment]
ccrap.... WTH??

**Comment by oshmoun** [comment]
your guess is as good as mine :D 
maybe it's worth it to try out with hwc2
https://github.com/sonyxperiadev/device-sony-common/pull/375

**Comment by humberos** [comment]
The problem is... 
    start bootanim

**Comment by humberos** [comment]
https://github.com/sonyxperiadev/device-sony-common/pull/376

**Pull request closed without merging**
