### PR TITLE
Drop android.hardware.power@1.0 service and impl

### PR DESCRIPTION
**Pull request by luk1337**
* Since we are providing our own service and
  power.$(TARGET_DEVICE) is dead there's no
  reason to build it.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Before this gets merged, notice that the 1.3 power HAL was [added to `common-packages.mk`](https://github.com/sonyxperiadev/device-sony-common/commit/7e1074ee4ca150c434197cb92329c6f98b94c9ac) instead of the usual `common-treble.mk`. Do we want to correct this for consistency?

**Comment by luk1337** [comment]
Umm
https://github.com/sonyxperiadev/device-sony-common/commit/7e1074ee4ca150c434197cb92329c6f98b94c9ac

**Comment by luk1337** [comment]
I don't want to correct this for consistency. I'm just removing it cause only a single `android.hardware.power/IPower` interface can be registered and supposedly it's not always that the power HAL we want registers it first. At least according to slack messages in #general.

**Comment by kholk** [comment]
Solves issues _at least_ when Android wants to use power@1.2 interfaces.

This PR is CRITICAL. MERGE!

**Pull request merged**
