### PR TITLE
[R] modem-config : Add Chunghwa Telecom modem-config file

### PR DESCRIPTION
**Pull request by RRRua**
Dumped from XQ-AT52_Customized TW_58.1.A.5.55-R4B
Tested on PixelExperience eleven

### CODE REVIEW

**Comment by RRRua** [comment]
Screenshot_20210410-232505
Screenshot_20210410-232521
Screenshot_20210410-232547

**Comment by RRRua** [comment]
Screenshot_20210410-232505
Screenshot_20210410-232521
Screenshot_20210410-232544

**Comment by MarijnS95** [comment]
@RRRua Why was this closed? Seems valid to me.

You can click the edit button in the top right to change the target branch to `r-mr1` (or `q-mr1` for everyones benefit, R is rebased on top). Please do not waste more PR IDs and email noise on such simple changes.

**Comment by RRRua** [comment]
@MarijnS95 Path seems still wrong for me, I got those errors:
[logcat_04-11-2021_01-11-16.txt](https://github.com/sonyxperiadev/device-sony-common/files/6290422/logcat_04-11-2021_01-11-16.txt)

**Comment by MarijnS95** [comment]
@RRRua Mind sharing full logs (of this particular section)? Some of these are non-fatal, and the paths are usually printed. You can check via `adb` what `mbn` files are available too.

**Comment by RRRua** [comment]
[logcat_modem.txt](https://github.com/sonyxperiadev/device-sony-common/files/6290448/logcat_modem.txt)

@MarijnS95 Are these enough for the find?
How do I check what mbn files are  available via adb?

**Comment by RRRua** [comment]
[logcat_04-11-2021_01-45-43.txt](https://github.com/sonyxperiadev/device-sony-common/files/6290453/logcat_04-11-2021_01-45-43.txt)
Are these enough for the finding?
How do I check what mbn files  are available via adb?

**Comment by MarijnS95** [comment]
I don't understand the point behind passing `-v long` but oh well, can't have nice things I guess. The logs are insanely hard to read.

There doesn't seem to be much logging for `modem-config` but there are a ton of expired lines, that isn't helpful either. PE and IMS is something I won't burn my hands on as well.

**Comment by RRRua** [comment]
[nile-discovery-modem-switcher.txt](https://github.com/sonyxperiadev/device-sony-common/files/6329577/nile-discovery-modem-switcher.txt)
@MarijnS95 Sorry for the disturbance I caused during last log action, since it was done by a root app.
This time I tried to properly using logcat with gerp modem-switcher and noticed weird behavior of the modem that seems not an IMS bug:
Mobile network randomly connects and disconnects and the log happens
When the last line in log happened, the mobile network persists connected

**Comment by RRRua** [comment]
[sodp11-nile-discovery-modem-switcher.txt](https://github.com/sonyxperiadev/device-sony-common/files/6489024/sodp11-nile-discovery-modem-switcher.txt)
Hmm, getting same error on SODP11, closing this for now

**Pull request closed without merging**
