### PR TITLE
sony-common: Allow lid to control sleep/wake behaviour

### PR DESCRIPTION
**Pull request by alviteri**
https://android.googlesource.com/platform/frameworks/base/+/android-7.1.1_r6/core/res/res/values/config.xml#688

This allows flip covers such as the Sony Smart Style Cover
to suspend or wake the device.

### CODE REVIEW

**Comment by rcstar6696** [comment]
those changes in overlay are in the devices trees already 
because not all device have it

**Comment by alviteri** [comment]
@rcstar6696 ..... @jerpelea told me to make it common ... see 

https://github.com/sonyxperiadev/device-sony-satsuki/pull/38

**Comment by rcstar6696** [comment]
here you can its defined for all other too in device trees for example castor common  https://github.com/sonyxperiadev/device-sony-castor_windy/commit/05a4ac9c7c25d50c49f6741bfd6cfbd7b3052776

**Comment by alviteri** [comment]
man .... alin said to move it to common because all have magnetic covers so I am moving them to common

**Comment by jerpelea** [comment]
this should be a common prop. all devicss have covers!

**Pull request merged**
