### PR TITLE
Set more volume steps for voice call and media

### PR DESCRIPTION
**Pull request by luk1337**
Taken from:
 * https://android.googlesource.com/device/google/marlin/+/f4b5315f48096edaa617f46f5f0c316e524ef6d9
 * https://android.googlesource.com/device/google/wahoo/+/2ced5331261a7303d870e86741b3a67875539a81

### CODE REVIEW

**Comment by jerpelea** [comment]
Did you test all 25 steps?

**Comment by luk1337** [comment]
I didn't test this on SOD yet but I don't see how could it cause any issues. It's only adding additional steps between current min-max.

**Comment by jerpelea** [comment]
please test it

**Comment by luk1337** [comment]
Yes, all 25 steps are working. Just tried it on my pioneer.

**Pull request merged**
