### PR TITLE
[WIP] Init optimizations

### PR DESCRIPTION
**Pull request by ix5**
I mainly made this PR to spite Angelo.

### CODE REVIEW

**Comment by ix5** [comment]
Requires changes to fstab in platform gits.

**Comment by oshmoun** [comment]
instead of hardcoding hal versions, maybe consider adding and using props or are props unavailable at this init stage?

**Comment by ix5** [comment]
> instead of hardcoding hal versions, maybe consider adding and using props or are props unavailable at this init stage?

I've added what you've asked for to evaluate for others, but please read my opinion on that in https://github.com/sonyxperiadev/device-sony-common/pull/751/commits/1a796b881adc5583d30dcbf2d7cd58966ad79f49

**Comment by MarijnS95** [comment]
And as we discussed this property doesn't nearly cover all cases:
- Pacakges in common-treble.mk (only linked here by means of a comment)
- Vintf
- AOSP initrc service naming that may change or be updated

Trying to make this generic and "future proof" (which I was initially all for) is merely shooting ourselves in the foot.

**Comment by chris42** [comment]
Regarding Loire/Kugo this is a complicated PR. The regular legacy build for Loire runs on the q-mr1-legacy branch, which hasn't seen the changes over the last time. 
Hence this PR and init optimizations are on a different path which will not affect Loire.

**Pull request merged**
