### PR TITLE
[master] Use new audio_effects_conf v2.0 (xml) 

### PR DESCRIPTION
**Pull request by humberos**
Convert .conf file by using this tool:

https://github.com/luk1337/aeffects-conf2xml

Thanks to @luk1337 for this one!

Tested on loire and tone platforms.

### CODE REVIEW

**Comment by luk1337** [comment]
This is wrong. Please redo it using my tool ~ https://github.com/luk1337/aeffects-conf2xml
image

**Comment by humberos** [comment]
Hi, first of all thanks for the tip.
I've just put the same UID that is already present in old.conf file.
Also I have no log errors from EffectsConfig loader.

ping @jerpelea 
Please let  me know if we should use the results from @luk1337 tool.

**Comment by luk1337** [comment]
Yeah, not having errors doesn't mean it's right especially since you had them due to making android load wrong library...
Also what uuid are you talking about `1d0a1a53-7d5d-48f2-8e71-27fbd10d842c` is nowhere to be found in this tree.

**Comment by luk1337** [comment]
For me it just looks like you copy pasted `1d0a1a53-7d5d-48f2-8e71-27fbd10d842c` from Google trees without actually looking at your current audio_effects.conf.

**Comment by humberos** [comment]
oh! god....
you're right
my mistake!

**Comment by luk1337** [comment]
Would be cool if you linked my tool in the description ^.^

**Comment by luk1337** [comment]
s/description/commit message/

**Comment by humberos** [comment]
sure!
Thanks a lot!

**Comment by luk1337** [comment]
Also you can verify it using `adb shell dumpsys media.audio_flinger | sed '/Clients:/q'`, it'll say `XML effect configuration loaded successfully.` if everything is alright.

**Comment by humberos** [comment]
adb shell dumpsys media.audio_flinger | sed '/Clients:/q'
Libraries NOT loaded:
Libraries loaded:
 Library loudness_enhancer
  path: /vendor/lib/soundfx/libldnhncr.so
  Loudness Enhancer / The Android Open Source Project
    UUID: fa415329-2034-4bea-b5dc-5b381c8d1e2c
    TYPE: fe3199be-aed0-413f-87bb-11260eb63cf1
    apiVersion: 00020000
    flags: 00000008
 Library qcom_pre_processing
  path: /vendor/lib/soundfx/libqcomvoiceprocessing.so
  Noise Suppression / Qualcomm Fluence for Sony Devices
    UUID: 72d30d20-0306-11e6-9860-0002a5d5c51b
    TYPE: 58b4b260-8e06-11e0-aa8e-0002a5d5c51b
    apiVersion: 00020000
    flags: 00020203
  Acoustic Echo Canceler / Qualcomm Fluence for Sony Devices
    UUID: 685707c0-0306-11e6-be79-0002a5d5c51b
    TYPE: 7b491460-8d4d-11e0-bd61-0002a5d5c51b
    apiVersion: 00020000
    flags: 00020203
 Library offload_bundle
  path: /vendor/lib/soundfx/libqcompostprocbundle.so
  (no effects)
 Library proxy
  path: /vendor/lib/soundfx/libeffectproxy.so
  Visualizer / The Android Open Source Project
    UUID: ec7178ec-e5e1-4432-a3f4-4657e6795210
    TYPE: e46b26a0-dddd-11db-8afd-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400008
  Insert Preset Reverb / NXP Software Ltd.
    UUID: f3e178d2-ebcb-408e-8357-0002a5d5c51b
    TYPE: 47382d60-ddd8-11db-bf3a-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400048
  Auxiliary Preset Reverb / NXP Software Ltd.
    UUID: 1b78f587-6d1c-422e-8b84-0002a5d5c51b
    TYPE: 47382d60-ddd8-11db-bf3a-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400001
  Insert Environmental Reverb / NXP Software Ltd.
    UUID: b707403a-a1c1-4291-9573-0002a5d5c51b
    TYPE: c2e5d5f0-94bd-4763-9cac-4e234d06839e
    apiVersion: 00020000
    flags: 00400048
  Auxiliary Environmental Reverb / NXP Software Ltd.
    UUID: 48404ac9-d202-4ccc-bf84-0002a5d5c51b
    TYPE: c2e5d5f0-94bd-4763-9cac-4e234d06839e
    apiVersion: 00020000
    flags: 00400001
  Equalizer / NXP Software Ltd.
    UUID: c8e70ecd-48ca-456e-8a4f-0002a5d5c51b
    TYPE: 0bed4300-ddd6-11db-8f34-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400048
  Virtualizer / NXP Software Ltd.
    UUID: d3467faa-acc7-4d34-acaf-0002a5d5c51b
    TYPE: 37cc2c00-dddd-11db-8577-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400250
  Dynamic Bass Boost / NXP Software Ltd.
    UUID: 14804144-a5ee-4d24-aa88-0002a5d5c51b
    TYPE: 0634f220-ddd4-11db-a0fc-0002a5d5c51b
    apiVersion: 00020000
    flags: 00400248
 Library downmix
  path: /vendor/lib/soundfx/libdownmix.so
  Multichannel Downmix To Stereo / The Android Open Source Project
    UUID: 93f04452-e4fe-41cc-91f9-e475b6d1d69f
    TYPE: 381e49cc-a858-4aa2-87f6-e8388e7601b2
    apiVersion: 00020000
    flags: 00000008
 Library visualizer_hw
  path: /vendor/lib/soundfx/libqcomvisualizer.so
  (no effects)
 Library visualizer_sw
  path: /vendor/lib/soundfx/libvisualizer.so
  (no effects)
 Library reverb
  path: /vendor/lib/soundfx/libreverbwrapper.so
  (no effects)
 Library bundle
  path: /vendor/lib/soundfx/libbundlewrapper.so
  Volume / NXP Software Ltd.
    UUID: 119341a0-8469-11df-81f9-0002a5d5c51b
    TYPE: 09e8ede0-ddde-11db-b4f6-0002a5d5c51b
    apiVersion: 00020000
    flags: 00000050
XML effect configuration loaded successfully.
Clients:

**Comment by luk1337** [comment]
Looks good to me.

**Comment by humberos** [comment]
Thanks have a great 2018!
Cheers!

**Pull request merged**
