### PR TITLE
Enforce usage of vintf manifest

### PR DESCRIPTION
**Pull request by ix5**
Check manifest and compatibility_matrix files at build time

### CODE REVIEW

**Comment by ix5** [comment]
Running this for about 2 weeks without issues, may need testing for tama with keymaster stuff?

**Comment by ix5** [comment]
The side effect of this change is that existing "DualSIM Patchers" will no longer work, since the second instance of the HALs is not in the single-SIM manifest.
The patchers will have to include updated `manifest.xml` files (but don't worry, we're on this already).

**Comment by ix5** [comment]
Ready for merge.

**Comment by MarijnS95** [comment]
Running this since the creation of the PR on devices from pretty much all platforms (Suzu, Discovery, Mermaid, Akatsuki), no regressions. Has the go-ahead from me :+1:

**Comment by Paulbouchara** [comment]
Running fine on my devices (kagura, maple, Akatsuki)
Good to go !

**Comment by ix5** [comment]
It's kind of funny, because current `master`/Q throws an error for `radio@1.2` even without this build flag set... ;)

But yeah, this buildvar is enabled on all devices with `SHIPPING_API_LEVEL >= 26` anyway (see [build/make/core/config.mk](https://android.googlesource.com/platform/build/+/refs/tags/android-q-preview-6/core/config.mk#672)), so @MarijnS95 I'd be very surprised if you saw any difference :)

This PR is mainly for legacy devices, and I've tested extensively on tone.

**Comment by MarijnS95** [comment]
Which basically means enforcement is "useless" on Pie, as we've seen before. Good to know that Q reminds us though ^^

**Comment by ix5** [comment]
Already done by #640 
`VINTF_ENFORCE_NO_UNUSED_HALS` is an internal build system var and should not be set.

**Pull request closed without merging**
