### PR TITLE
vintf: Added vendor.qti.hardware.camera.postproc

### PR DESCRIPTION
**Pull request by hellobbn**

### CODE REVIEW

**Comment by MarijnS95** [comment]
add*

And this isn't the right file.

**Comment by hellobbn** [comment]
So create a new file for that? Ok

**Comment by hellobbn** [comment]
I have put them in a new xml file

**Comment by Haxk20** [comment]
@hellobbn Rebase please

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
