### PR TITLE
sony-common: add recovery headers

### PR DESCRIPTION
**Pull request by alviteri**
needed for inline kernel system build
this needs extra commit to call this from bootable/recovery/minui/Android.mk
https://github.com/SonyAosp/platform_bootable_recovery/commit/8f6832b3ad16bdad4af298315e8fcfb3f6b41fc8

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
maple poplar dora recovery works

**Comment by alviteri** [comment]
ping @kholk

**Comment by Bitti09** [comment]
are we doing inline kernel build on default sod settings?
if  i remember right  the prebuilt one is used by default .

**Comment by alviteri** [comment]
This is not needed here .. but is usefully for all external projects basing ROMs for Sony Xperia on this source

**Comment by jerpelea** [comment]
Headers should be properly exported.There is no meed for a local copy

**Pull request closed without merging**
