### PR TITLE
vintf: Upgrade wifi hal to 1.3

### PR DESCRIPTION
**Pull request by sjllls**
All work fine on both 1.2 and 1.3, we update it for more new features

### CODE REVIEW

**Comment by MarijnS95** [comment]
Well, thanks for making me rebase again :no_mouth:

**Comment by jerpelea** [comment]
always a pleasure :)

**Comment by sjllls** [comment]
> Well, thanks for making me rebase again no_mouth
> 
> Also, were are updating this version first and foremost for _correctness_. The default wifi HAL implements v1.3, and our manifest should reflect that.

Yeah, should we upgrade [this](https://github.com/sonyxperiadev/device-sony-common/blob/master/common-treble.mk#L41)?
Thanks for your suggestion !

**Comment by MarijnS95** [comment]
@sjllls No, I mean that _that_ (correctness) is the reason for updating to 1.3, not "just because we can" or "because maybe new features". Doesn't matter now, commit has been merged already.

**Comment by jerpelea** [comment]
we should move to 1.3 for the new features that we will soon use

**Comment by MarijnS95** [comment]
@jerpelea We have already moved to 1.3, with this bump in the vintf.

Google hardly ever updates the _minor_ HAL version number, I think to save on required edits elsewhere. Instead, the default `1.0` HAL implements the V1.3 HIDL.

**Comment by sjllls** [comment]
> @jerpelea We have already moved to 1.3, with this bump in the vintf.
> 
> Google hardly ever updates the _minor_ HAL version number, I think to save on required edits elsewhere. Instead, the default `1.0` HAL implements the V1.3 HIDL. (There's your answer @sjllls wink)
> 
> Here I am again hoping for Google to migrate to the new `vintf_fragments` option, as this allows the manifest version to be bundled and properly incremented with the implementation itself, where it belongs.

Thanks a lot!

**Pull request merged**
