### PR TITLE
[R/Q] android.bp: Remove hidltransport and hwbinder from shared libs

### PR DESCRIPTION
**Pull request by Haxk20**
In Android R libhwbinder and libhidltransport are no longer available to use.
Thus let's remove the libraries.

### CODE REVIEW

**Comment by MarijnS95** [comment]
I would have appreciated a more elaborate explanation in the commit: why these libraries are still there but can't be linked from a `vendor` context, why there is no replacement -> whether this has always been a transitive (hence unnecessary) dependency, and finally if other basic dependencies (that are not directly referenced in code afaik) are transitively included as well such as `libhidlbase`.

**Comment by Haxk20** [comment]
@MarijnS95 We have to remove them because Android 10 deprecates those 2 libraries. That doesnt mean that the stuff they provided no longer exists tho.
libhidlbase got the role of having all the symbols of libhidltransport and libhwbinder.

**Comment by MarijnS95** [comment]
@Haxk20 Correct, that's the kind of explanation I expected in the commit, together with sources backing up these claims:

https://android.googlesource.com/platform/system/libhidl/+/8f65ba713e73b40dc58dd7a8a702a96d6c1c2181
https://android.googlesource.com/platform/system/libhidl/+/a46371d5b3ffd08808ae93ec420721345738ec65
https://android.googlesource.com/platform/system/libhwbinder/+/09a8725d56b168668a11530537c9738f4bc58a90

All three are on `android-10` tags as well which is why I asked you test and PR these for Q (and have R rebased on top of that).

**Comment by jerpelea** [comment]
please push to Q-mr1

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
