### PR TITLE
sony-common: Build SimToolKit

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
stk should not be built on non  gsm targets!

**Comment by alviteri** [comment]
Mmm my question is why z1 z3 and z5p in stock have it ..... anyway thanks

**Comment by AdFad666** [comment]
This would put it on WiFi tablets, you'll have to add it to each device repo (yay more work for you :snowman:)

**Comment by alviteri** [comment]
@AdFad666 there is a way more easy for it ... just @jerpelea not needs close this ;)

**Pull request closed without merging**
