### PR TITLE
[WIP] Readd gps conf

### PR DESCRIPTION
**Pull request by ix5**
Might wanna overhaul it while we're at it...

Needs https://github.com/sonyxperiadev/vendor-qcom-opensource-location/pull/22 and https://github.com/sonyxperiadev/repo_update/pull/119

### CODE REVIEW

**Comment by jerpelea** [comment]
why?

**Comment by ix5** [comment]
I'll add the needed patches for qcom/gps

**Comment by jerpelea** [comment]
link?

**Comment by ix5** [comment]
https://github.com/sonyxperiadev/repo_update/blob/master/repo_update.sh#L63-L66
These need to go, and a patch to opensource location.

**Comment by jerpelea** [comment]
do them and we can see

**Comment by jerpelea** [comment]
but instead of adding the conf back here you should update the one from the gps repo otherwise it will create conflicts to the downstream projects

**Comment by ix5** [comment]
https://github.com/omnirom/android/blob/1bcf6a6f5c082107c29977555bbd123fbcf7b47c/remove.xml#L111
https://github.com/omnirom/android_hardware_qcom_gps/tree/android-10/
SonyAOSP isn't on 10 yet afaics https://github.com/SonyAosp/platform_hardware_qcom_sdm845_gps

We're the only ones still applying those reverts on Q.

**Pull request merged**
