### PR TITLE
camera: rename camera props with vendor prefix

### PR DESCRIPTION
**Pull request by alviteri**
following sonyxperiadev/hardware_qcom_camera commit 3ee7096ef94bad27f353cf4ff2320dd4f5c5f757

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
will be removed

**Comment by alviteri** [comment]
just remember yoshino needs persist.vendor.camera.lib2d.rotation or cam pics are rotated

**Comment by alviteri** [comment]
last time only yoshino was affected

**Comment by jerpelea** [comment]
tested maple and works fine

**Pull request closed without merging**
