### PR TITLE
ramdump cleaner - common part

### PR DESCRIPTION
**Pull request by aolexiy**
This adds ramdump cleaner for loire & tone & yoshino platforms. Please note that it depends on selinux change specific for the each platform, uploaded separately.

### CODE REVIEW

**Comment by aolexiy** [comment]
@jerpelea - please have a look, this is the common part, uploading the platform selinux patches as well

**Comment by jerpelea** [comment]
please remove the  "init.common.rc: move to a separate module " patch

**Comment by aolexiy** [comment]
SElinux part changed, no userdebug & eng variants specific directory, rdimage_block_device and rdclean_exec types are defined for all variants, rdclean_exec label as well, the rest is skipped for user.

**Comment by aolexiy** [comment]
@jerpelea - simplified, dropped init.*rc change thus it's now a single patch, added core class to service and enabled it

**Comment by jerpelea** [comment]
selinux rules shoulg go to the selinux folder

**Pull request merged**
