### PR TITLE
Finally unbreak dualsim :)

### PR DESCRIPTION
**Pull request by Quarx2k**
Fix typo.

### CODE REVIEW

**Comment by Myself5** [comment]
@Quarx2k I'd be intrested in what is needed for the dualsim devices to work.
Do you also require some blob related changes in comparision to a non dsds phone or is using your commit and the proper defconfig to append the proper dtb (so that sdcard is working too) enough?

**Comment by Quarx2k** [comment]
Yes sdcard works fine. Everything works except 5ghz wifi.
You need this commit, ds dtb and this blob https://github.com/Quarx2k/device-sony-ivy_dsds/blob/cm-13.0/temp/rild
Tommorrow i check what wrong with AOSP rild and hopefully make a patch, but for now only rild blob is solution.

**Comment by zachariasmaladroit** [comment]
@Quarx2k where did that rild originate from ? please let us know what is wrong with the original rild,

Great work ! :+1:

**Comment by Quarx2k** [comment]
rild from sony stock 6.0.1 ds rom.
I debugged aosp rild, there one problem. 
RILD1 connects to qmi RIL[0] socket (it's ok), but RILD2 connects also to qmi RIL[0], but should to RIL[1]. Thats why ril-daemon2 constantly crashing and IMEI for sim2 not available.
Probably should be easy to fix, will check tomorrow.

**Comment by Myself5** [comment]
The 5GHz WIFI is something @AdFad666 might be able answer. He said throwing out the SIM card and reinserting it fixes 5GHz WIFI (its still something which has to get solved properly).

Also wouldn't there be any commits be needed for AOSP for general DualSIM Support? Like Software/UI Wise or does all of that work?

Cause if everything works with AOSP, thats something @jerpelea might be intrested in, in reference to our last dsds discussions :P

**Comment by zachariasmaladroit** [comment]
From my knowledge the Dual SIM support should be there starting with Lollipop,

CyanogenMod builds further on that,

not really sure if the Kernel-side needs further modifications but I also ported over the SIM_DETECT driver and it seemed to have helped (as did Quarx2k),

I don't own a dual sim device and also didn't get any meaningful logcat, dmesg, etc. output up until now - so it's kind of hard to debug

**Comment by Quarx2k** [comment]
I think SIM_DETECT driver not really needed. I added it to debug simcards on kernel level.
In stock rom it used for SemcSimDetection, which reboot device when simcard removed/inserted.

**Comment by AdFad666** [comment]
Yes, for me on my ivy, if you:

1. disable WiFi
2. insert a SIM
3. reboot the device
4. enable WiFi

you will be able to connect to 5GHz WiFi. This but also affects karin_windy butis impossible to solve in the same way due to lack of RIL.

Fortunately for ivy this fix persists across reboots and power downs, even when the SIM has been removed.

**Comment by Quarx2k** [comment]
AOSP rild works fine, no need any patches, just need change socket name :)

**Comment by alviteri** [comment]
welcome to this family @Quarx2k xD

**Pull request merged**
