### PR TITLE
[n-mr1] sony: common: Override android filesystem config

### PR DESCRIPTION
**Pull request by humberos**
Override android file system config and allow derived projects
to use their particular implementation.

Add some SONY UID and enabled CAF UID references.
They are disabled for now.

Sony UIDs was extracted from
https://github.com/LineageOS/android_device_sony_kitakami-common/commit/5625ab18f372514ea97294b8b21351aae4fda025

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I2d570e5ade4220f7a06e4a064317b149a957ff5b

### CODE REVIEW

**Comment by humberos** [comment]
ping @alviteri 
please, could check this on aosp builds ?
thank you!

**Comment by alviteri** [comment]
Oh this is good for stock cam libs too

**Comment by alviteri** [comment]
@humberos I don't know if this help you .. but this breaks sensors on M .... can't test on N yet

**Comment by humberos** [comment]
Oh, I will make a patch for M
This one was tested on N (Omni) 
Thanks

**Comment by humberos** [comment]
Patch updated.
I've just preserved the current status of header (AOSP).
We could develop on sensors (CAF UID) later if it is the case.

**Comment by humberos** [comment]
it requires
https://android-review.googlesource.com/#/c/358909/

**Pull request closed without merging**
