### PR TITLE
[master] hardware: ssc: Kona sensors

### PR DESCRIPTION
**Pull request by ix5**
**DONOTMERGE** Just for bringup purposes
@kholk

### CODE REVIEW

**Comment by kholk** [comment]
The first commit is a sure merge: please, split them and let's get the first one in asap.

**Comment by ix5** [comment]
Pushed off the updated non-edo-specific configs.

Someone please build-test this!

**Comment by kholk** [comment]
I think @MarijnS95 has tested it already, since he gave me an image with these files in, but I'm not sure whether it was your commit or a self-baked one.

Please Marijn, can you confirm?

**Comment by MarijnS95** [comment]
Apologies, I have not added these files yet - so they shouldn't be in your image either @kholk! Well, that is, until now, the patch is now in my tree and will be in the next vendor image :grimacing:

**Review by MarijnS95 — APPROVED** [review]
Edo is magical. This is the first platform where sensors "just work" out of the box, no random crashes around SSC because we're missing an obscure `*pd` userspace binary somewhere, or corruption on persist.

Thanks!

**Pull request merged**
