### PR TITLE
use $(KONA) to replace hardcoded sm8250

### PR DESCRIPTION
**Pull request by LogicFan**

### CODE REVIEW

**Review by MarijnS95 — CHANGES_REQUESTED** [review]
No need for this, https://github.com/sonyxperiadev/device-sony-common/pull/886 will be auto-rebased into it.

Rather, help us out with replacing the rest of the platforms https://github.com/sonyxperiadev/device-sony-common/pull/886#issuecomment-1109656350.

**Comment by LogicFan** [comment]
> No need for this, #886 will be auto-rebased into it.
> 
> Rather, help us out with replacing the rest of the platforms [#886 (comment)](https://github.com/sonyxperiadev/device-sony-common/pull/886#issuecomment-1109656350).

I can modify for the other platforms, but since I don't have a device other than edo platform, it's hard to verify the correctness.

also I think there will be a merge conflict to for the auto-rebase of this one?

**Comment by MarijnS95** [comment]
> I can modify for the other platforms, but since I don't have a device other than edo platform, it's hard to verify the correctness.

I've done this myself... https://github.com/sonyxperiadev/device-sony-common/pull/888

> also I think there will be a merge conflict to for the auto-rebase of this one?

That merge conflict for introducing `sm8350` and/or removing older unsupported SoCs will be addressed by using `$(LAHAINA)`.

**Comment by jerpelea** [comment]
no longer needed

**Pull request closed without merging**
