### PR TITLE
power: add 8994 platform

### PR DESCRIPTION
**Pull request by Kali-**

### CODE REVIEW

**Comment by jerpelea** [comment]
Link to original source and commit message

**Comment by AdFad666** [comment]
this depends on libqti-perfd-client.so and mpdecision, I thought we didn't want those?

We'll likely have to remove @kholk 's cpuquiet

**Comment by jerpelea** [comment]
Not necessarly. We can work around

**Comment by Kali-** [comment]
mpdecision is not used on 8994 and lib libqti-perfd-client.so is not required

bro ...

**Pull request merged**
