### PR TITLE
Audio effect

### PR DESCRIPTION
**Pull request by richardtullberg**
@oshmoun 
These fixes might solve your BT issues.

### CODE REVIEW

**Comment by luk1337** [comment]
Do they actually load?

**Comment by luk1337** [comment]
https://github.com/sonyxperiadev/device-sony-common/blob/master/hardware/voice_processing/voice_processing_descriptors.c#L28
https://github.com/sonyxperiadev/device-sony-common/blob/master/hardware/voice_processing/voice_processing_descriptors.c#L40

**Comment by luk1337** [comment]
tl;dr I took a look at AOSP audio HAL. It seems to load `/vendor/lib/soundfx/libqcomvoiceprocessingdescriptors.so` or `/system/lib/soundfx/libqcomvoiceprocessingdescriptors.so` depending on your setup and that's where it gets UUIDs from. So if this commit fixes your BT issues then it means that somehow your voice processing is broken and disabling it is the workaround for it cause obviously it wouldn't load it properly with suggested by @richardtullberg UUIDs.

**Comment by luk1337** [comment]
His changes would work tho if you decided to drop custom `libqcomvoiceprocessingdescriptors` library.

**Comment by jerpelea** [comment]
@richardtullberg which path do we take ?

**Comment by richardtullberg** [comment]
Let's just leave it be if it works.

**Comment by jerpelea** [comment]
@richardtullberg the problem is that on n-mr1 we use this patch and on o we closed it
we should test all Android versions and choose 1 direction 
now it is confusing !

**Comment by luk1337** [comment]
I have alternative patch for that ~ https://gist.github.com/1a96bff6a6d99cddc0fda6baea78e3b6

**Comment by luk1337** [comment]
It addresses everything I mentioned here.

**Comment by jerpelea** [comment]
@richardtullberg?

**Comment by richardtullberg** [comment]
Let's do it like @luk1337 does it then

**Comment by jerpelea** [comment]
@luk1337 please pr on the following branches:

n-mr1-legacy 
n-mr1
o-mr0
master

**Pull request closed without merging**
