### PR TITLE
init: qcrild.rc : Add vendor prefix to ril-daemon

### PR DESCRIPTION
**Pull request by ShujathMohd**
qcrild.rc is attempting to stop ril-daemon which doesnt exist (https://github.com/sonyxperiadev/device-sony-common/blob/s-mr1/rootdir/vendor/etc/init/qcrild.rc#L9) and errors out with the below message.

"init: Command 'stop ril-daemon' action=vendor.rild.libpath=/odm/lib64/libril-qc-hal-qmi.so (/vendor/etc/init/qcrild.rc:9) took 0ms and failed: service ril-daemon not found."

Instead we have vendor.ril-daemon service starting in the background.

"init: starting service 'vendor.ril-daemon'..."

Add the vendor prefix to ril-daemon.

Fixes the buggy sim detection on S.

### CODE REVIEW

**Review by bartcubbins — APPROVED** [review]

**Comment by bartcubbins** [comment]
LGTM. Reference:
https://android.googlesource.com/platform/hardware/ril/+/83035b57fc6f63f4e80c3a424f09a867150e3bbe

**Comment by MarijnS95** [comment]
Please add the reference link to the commit.

That commit is from 2018, should this also be applied to at least r-mr1?

**Comment by jerpelea** [comment]
cherry-picked

**Comment by bartcubbins** [comment]
`should this also be applied to at least r-mr1?`
yes, as I can see

**Comment by ShujathMohd** [comment]
> cherry-picked

Thanks Alin,
Its piked on R currently, Need it for S too.

**Comment by MarijnS95** [comment]
> Thanks Alin, Its picked on R currently, Need it for S too.

It's definitely on S:

image

**Comment by ShujathMohd** [comment]
> > Thanks Alin, Its picked on R currently, Need it for S too.
> 
> It's definitely on S:
> 
> image

Oops. my bad...
Thanks Marijn

**Pull request closed without merging**
