### PR TITLE
Implement RGB sync

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by jerpelea** [comment]
we should use the same blink for all devices

**Comment by luk1337** [comment]
Yeah, someone has to do tone and yoshino then we can merge this.

**Comment by jerpelea** [comment]
yep

**Comment by jerpelea** [comment]
you can modify the dts for loire, tone and yoshino

**Comment by jerpelea** [comment]
don't forget the LED drivers

**Comment by luk1337** [comment]
Uh, I think loire isn't using qpnp led, am I right?

**Comment by jerpelea** [comment]
the hal should be the same for all

**Pull request merged**
