### PR TITLE
[WIP] init: adb_tcp: Use "compatible" ES adb port prop

### PR DESCRIPTION
**Pull request by ix5**
Needs change in ExtendedSettings to update from `adb.network.*` to `vendor.adb.network`.

(Original PR content was to rename per-proxy and also act on the renamed multisim prop)

### CODE REVIEW

**Comment by jerpelea** [comment]
remove the old properties

**Comment by jerpelea** [comment]
@ix5 please rebase

**Comment by ix5** [comment]
Rebased

**Comment by jerpelea** [comment]
this patch needs to be splitted in smaller patches 
I will handle the service naming

**Comment by jerpelea** [comment]
please rebase

**Pull request merged**
