### PR TITLE
allow override HALs

### PR DESCRIPTION
**Pull request by alviteri**
needed by external project placing sony hals under hardware/*/*

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@kholk to avoid this problem https://github.com/SonyAosp/platform_manifest/commit/6288e76459ee44fa25a4cdfee2980b3c2806e752


this PR should be enabled since i will move the things to hardware/sony

**Comment by kholk** [comment]
Uhm, that looks messy.... like... a lot.

**Comment by alviteri** [comment]
This let external project set own hals this will not affect the mainline project

**Comment by alviteri** [comment]
Google way is messy putting hals wherever they want

**Pull request closed without merging**
