### PR TITLE
8.0 rild2

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
@pablomh @bartcubbins I can't remebert who of you guys have DSDS target

**Comment by pablomh** [comment]
That's me, but we still need @bartcubbins awesome work to be finished in tulip before I can test anything :(

**Comment by bartcubbins** [comment]
DS too

**Comment by pablomh** [comment]
Righ!! :/

**Comment by alviteri** [comment]
@jerpelea this can be merged since it follow aosp init ril changes

**Pull request merged**
