### PR TITLE
fix for the video stuttering

### PR DESCRIPTION
**Pull request by rudcode**

### CODE REVIEW

**Comment by Bitti09** [comment]
:+1:

**Comment by rudcode** [comment]
Will leave this open, but I think we need better implementation.

**Comment by Bitti09** [comment]
Ok, tested this fix with   a new build (repo sync yesterday):
youtube works without  stuttering even on  1080p

logcat  sometimes (mainly when switching video) shows this line:
10-03 14:37:23.849   646  1224 E rqbalance_ctl: Cannot connect to PowerServer socket

**Comment by djselbeck** [comment]
I think there is more going on.I observe real high cpu usage during VP9 decoding (checked with top). h264 seems fine though.

**Comment by Bitti09** [comment]
maybe some missing blobs for hw decode ?

**Comment by djselbeck** [comment]
I see that the qcom omx vp9 decoder is opened successfully. But still the device gets so hot vp9 fullhd decoding with kodi is impossible after some time

**Comment by djselbeck** [comment]
> 10-03 21:12:45.661   524  4428 I rqbalance_halext: OMX Decoder hint received.
> 10-03 21:12:45.661   524  4428 I RQBalance-PowerHAL: Setting video_decoding mode
> 10-03 21:12:47.188   524  4428 E rqbalance_halext: Unexpected argument. Bailing out.
> 10-03 21:12:47.189   524  4428 D rqbalance_halext: Arguments: 3
> 10-03 21:12:47.191   524  4428 D rqbalance_halext: Arg[0]: 0x101
> 10-03 21:12:47.198   524  4428 D rqbalance_halext: Arg[1]: 0x20e
> 10-03 21:12:47.199   524  4428 D rqbalance_halext: Arg[2]: 0x30e
> 10-03 21:12:47.199   524  4428 D rqbalance_halext: Arg[3]: 0xffffffff
> 10-03 21:13:17.161   524  4428 I rqbalance_halext: OMX Decoder hint received.
> 10-03 21:13:17.162   524  4428 I RQBalance-PowerHAL: Setting video_decoding mode


this seems to be the problem. This sometimes appears and then video is stuttering with around 1-3 fps. Seems like the lock cannot be acquired

**Comment by Bitti09** [comment]
youtube 1080p 60fps: same error appears in logcat

**Comment by djselbeck** [comment]
I think it maybe originating from here:
[](
https://android.googlesource.com/platform/hardware/qcom/audio/+/master/hal/audio_extn/audio_extn.c#100)

at least the parameters match

**Comment by Bitti09** [comment]
Log says:  Arguments: 3
in audio_platform_info
it says:
        <param key="perf_lock_opts" value="4, 0x101, 0x704, 0x20F, 0x1E01"/>

your link says: 
int perf_lock_opts[] = {0x101, 0x20E, 0x30E};

**Comment by djselbeck** [comment]
I was looking at the wrong things sorry. The video_decoding config in rqbalance for tone devices is to slow for applications like firefox. Created a pull request to change them to balanced.

https://github.com/sonyxperiadev/device-sony-tone/pull/76

**Comment by Bitti09** [comment]
@djselbeck  will test your recent changes tomorrow  if  you have some sample  videos / links please post them here

**Comment by Bitti09** [comment]
new error:
10-04 20:35:05.377   539  5006 E rqbalance_halext: Unexpected argument. Bailing out.
10-04 20:35:05.378   539  5006 D rqbalance_halext: Arguments: 3
10-04 20:35:05.379   539  5006 D rqbalance_halext: Arg[0]: 0x101
10-04 20:35:05.380   539  5006 D rqbalance_halext: Arg[1]: 0x20e
10-04 20:35:05.380   539  5006 D rqbalance_halext: Arg[2]: 0x30e

**Comment by djselbeck** [comment]
That is not new. It is the same error I posted above and it is unrelated to the video problems. It is just an unhandled power hint. The main problem of stuttering is that too many cores are offline.

**Comment by jerpelea** [comment]
updates?

**Comment by jerpelea** [comment]
@rudcode

**Pull request closed without merging**
