### PR TITLE
Disable Treble OMX by default.

### PR DESCRIPTION
**Pull request by alviteri**
Test: Manual use of Camera, Movies, Photos and YouTube apps.

Test: With CtsMediaTestCases.apk installed,
adb shell am instrument -e size small -w
'android.media.cts/android.support.test.runner.AndroidJUnitRunner'

Bug: 31399200
Change-Id: I6c027a29e5336d1834f6f5ee9f555e5c39834c3c

### CODE REVIEW

**Comment by jerpelea** [comment]
did you run cts?

**Comment by alviteri** [comment]
We are not fully treble ... At least on Oreo we will see on P ....

**Comment by jerpelea** [comment]
yes
did you test the case?

**Comment by alviteri** [comment]
Omx test passed and broken on another instance

**Pull request merged**
