### PR TITLE
common: binderize sensors HAL

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by luk1337** [comment]
You aren't building sensors service so how is this going to work?

**Comment by alviteri** [comment]
sensors test did on kugo without any conflicts .... @oshmoun can you remember me the problems presented on loire to disable this ?

**Comment by oshmoun** [comment]
yes the usual issue was the loss of compass functionality, and rarely the complete loss of sensors.
please try rebooting multiple times, since the issue was random. also, it wasn't only loire as it happened on tone too

**Comment by alviteri** [comment]
Can you also test ? Since Loire is not mine daily device

**Comment by pablomh** [comment]
Is testing needed on nile?

**Comment by jerpelea** [comment]
testing is neded on all

**Pull request merged**
