### PR TITLE
init: charger remove partition mount

### PR DESCRIPTION
**Pull request by abioteau**
Port commit https://github.com/sonyxperiadev/device-sony-common/commit/4b2af3ea9daba83332581d20ea49e240ae27c2d3 to n-mr1 branch

### CODE REVIEW

**Comment by jerpelea** [comment]
you can not remove the mount on android 7.1
https://github.com/sonyxperiadev/kernel/commit/58705ca63229eaa2bd04af12dd504c959f924543#diff-92b850d252477aff69cd191ad10cb77f
https://github.com/sonyxperiadev/kernel/commit/d7bfb7eaec3cb42e734482359f2920f7e5bf2d63#diff-92b850d252477aff69cd191ad10cb77f

**Comment by abioteau** [comment]
@jerpelea On Android 7.1 for no-legacy device, we have already the following commits in kernel (LA.UM.5.7.r1) for yoshino, loire and tone platforms : 
- https://github.com/sonyxperiadev/kernel/commit/4f82092e9c7220cb60428fa346fc96ebc6a43cd6
- https://github.com/sonyxperiadev/kernel/commit/c665e964a08b30d55341f493bb706b887caba0c7
- https://github.com/sonyxperiadev/kernel/commit/29ccf4c1dcf3ec94ecb7e33d72c446f6dcfea985

It seems enough. Furthermore on Android 7.1 for legacy device, we use another branch, n-mr1-legacy, for this repository.

**Comment by jerpelea** [comment]
fstab must be also updated with the patches from 8.1

**Comment by jerpelea** [comment]
if you have PR with all requiements I will accept them

**Comment by abioteau** [comment]
@jerpelea Thanks

**Pull request merged**
