### PR TITLE
[master] Audio bump to 5.0

### PR DESCRIPTION
**Pull request by ix5**
And also add some bt packages

Audio HAL also might need updates to `mixer_paths` https://github.com/ExplosiveLobster/device_sony_suzu/commit/535bb5dc7df965b69a823dd3b8ba292ec7224813

### CODE REVIEW

**Comment by kholk** [comment]
Felix, please, remove the draft status from this PR.
We need audio-5.0 on SM8150!

**Comment by MarijnS95** [comment]
@kholk I'm sorry to disappoint you, but I run 5.0 and as you know we both have the exact same audio issues on SM8150 :wink: 

Unfortunately, back to the drawing board it is :disappointed:

**Comment by kholk** [comment]
We still need 5.0 on SM8150: all devices having this chip (and SM6150, and the new ones) do
come with this: switching won't hurt anyone.

Unless you tell me that there are regressions.

**Comment by MarijnS95** [comment]
No regressions, I run this for months concurrently with the new A2DP offloading but it doesn't change anything for the issues we are facing now.

So by all means merge this (unless @ix5 wants to alter the commits), but don't expect magic to happen.

**Comment by ix5** [comment]
Note to self: Test `IBluetoothAudioProvidersFactory` especially on legacy devices

**Pull request merged**
